apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
type: Opaque
data:
  GROQ_API_KEY: Z3NrXzFGQXhVS0J6TmdadFVzZGdrcVk2V0dkeWIzRlk2OWpUeXRvN1doRk5nMzV2WHl1a0pqRVg=
  HF_TOKEN: aGZfc1VrbFhtU21JRkxUekFiR0pqaXRJS3hCRkhudFl2dUVuaw==
