apiVersion: v1
kind: Service
metadata:
  name: rag-service
spec:
  selector:
    app: rag-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: NodePort
  # type: LoadBalancer  # Change to NodePort if no cloud provider